spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/amigoscode
    username: amigoscode
    password: password

  jpa:
    hibernate:
      ddl-auto: create   # <== updated here
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  error:
    include-message: always
    include-binding-errors: always
